/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package quotes;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {

    @Test
    public void testgetRandomQuote() {
        Quote[] testQuotesArray = {new Quote("Ryan", "Java is cool")};
        assertEquals("Ryan:  \"Java is cool\"",  App.getRandomQuote(testQuotesArray));
    }

}
